### ISSUE TITLE
Resulting ELF crashes JFlash v7.92c

### ISSUE THREAD

**Issue by DualTachyon** [itzandroidtab/open_flashloader_template#2]
Were you able to test your template with a recent JLink?

I have been trying to implement a flash loader that works with Segger without success.
I have found many git repos, including yours and I cannot see what I'm doing wrong with mine.
I tried your project without modification and JFlash will quit unexpectedly as soon as I connect to a target.
I have a valid .xml in the JLinkDevices folder as indicated by Segger's wiki.

JFlash.log:

Connecting ...
 - Connecting via USB to probe/ programmer device 0
 - Probe/ Programmer firmware: J-Link V10 compiled Jan 30 2023 11:28:07
 - Probe/ Programmer S/N: <xxxxxxxx>

JLinkARM.log:
T0F48 128:592.296 - 33.295ms returns "O.K."
T0F48 128:592.336 JLINK_GetFirmwareString(...)
T0F48 128:592.336 - 0.022ms
T0F48 128:592.360 JLINK_GetSN()
T0F48 128:592.368 - 0.007ms returns <xxxxxxxx>
T0F48 128:592.656 JLINK_TIF_Select(JLINKARM_TIF_SWD)
T0F48 128:593.344 - 0.702ms returns 0x00
T0F48 128:593.360 JLINK_EMU_GetProductId()
T0F48 128:593.368 - 0.007ms
T0F48 128:593.472 JLINK_CORE_Select(0x60000FF == Cortex-M0)
T0F48 128:593.488 - 0.013ms
T0F48 128:593.496 JLINK_ExecCommand("Device = DP32G030", ...). 
T0F48 128:593.648   Flash bank @ 0xA0000000: SFL: Parsing sectorization info from ELF file
T0F48 128:593.664     FlashDevice.SectorInfo[0]: .SectorSize = 0x00000400, .SectorStartAddr = 0x00000000

**Comment by itzandroidtab** [comment]
Sorry, I did have a go with it on version V7.92g today (with a LPC1756 and a STM32L496VG). It connects correctly to the targets and it reads the content as expected. I did make [example](https://github.com/itzandroidtab/ofl_lpc1756_is25lq040b) available a few days ago.

If you run it using the debugger is it running as expected?

```
Reading entire flash chip ...
 - Connecting ...
  - Connecting via USB to probe/ programmer device 0
  - Updating firmware:  J-Link Pro V5-1 compiled Sep  7 2023 13:16:27
  - Replacing firmware: J-Link Pro V5-1 compiled Feb 23 2023 15:08:10
  - Waiting for new firmware to boot
  - New firmware booted successfully
  - Probe/ Programmer firmware: J-Link Pro V5-1 compiled Sep  7 2023 13:16:27
  - Probe/ Programmer S/N: 175104354
  - Device "STM32L496VG" selected.
  - Target interface speed: 8000 kHz (Fixed)
  - VTarget = 3.301V
  - InitTarget() start
  - SWD selected. Executing JTAG -> SWD switching sequence.
  - DAP initialized successfully.
  - InitTarget() end - Took 8.19ms
  - Found SW-DP with ID 0x2BA01477
  - DPIDR: 0x2BA01477
  - CoreSight SoC-400 or earlier
  - Scanning AP map to find all available APs
  - AP[1]: Stopped AP scan as end of AP map has been reached
  - AP[0]: AHB-AP (IDR: 0x24770011)
  - Iterating through AP map to find AHB-AP to use
  - AP[0]: Core found
  - AP[0]: AHB-AP ROM base: 0xE00FF000
  - CPUID register: 0x410FC241. Implementer code: 0x41 (ARM)
  - Found Cortex-M4 r0p1, Little endian.
  - FPUnit: 6 code (BP) slots and 2 literal slots
  - CoreSight components:
  - ROMTbl[0] @ E00FF000
  - [0][0]: E000E000 CID B105E00D PID 000BB00C SCS-M7
  - [0][1]: E0001000 CID B105E00D PID 003BB002 DWT
  - [0][2]: E0002000 CID B105E00D PID 002BB003 FPB
  - [0][3]: E0000000 CID B105E00D PID 003BB001 ITM
  - [0][4]: E0040000 CID B105900D PID 000BB9A1 TPIU
  - [0][5]: E0041000 CID B105900D PID 000BB925 ETM
  - Executing init sequence ...
   - Executing Reset (0, 0 ms)
    - Reset: Halt core after reset via DEMCR.VC_CORERESET.
    - Reset: Reset device via AIRCR.SYSRESETREQ.
   - Initialized successfully
  - Target interface speed: 8000 kHz (Fixed)
  - Found 1 JTAG device. Core ID: 0x2BA01477 (None)
  - Connected successfully
 - 4609 sectors, 2 ranges, 0x8000000 - 0x90FFFFF, 0x90000000 - 0x9FFFFFFF
 - WARNING: Flash bank 0 disabled, skipped.
 - WARNING: Flash bank 1 disabled, skipped.
 - Start of determining flash info (Bank 2 @ 0x08100000)
 - End of determining flash info
 - Flash bank info:
 - 4096 * 4 KB @ 0x08100000
 - Start of preparing flash programming
 - End of preparing flash programming
 - Blank checking 0x08100000 - 0x0811FFFF
 - Blank checking 0x08120000 - 0x0813FFFF
.......
 - Blank checking 0x090C0000 - 0x090DFFFF
 - Blank checking 0x090E0000 - 0x090FFFFF
 - Start of restoring
 - End of restoring
 - Target memory read successfully. (17825792 bytes, 1 range) - Completed after 53.573 sec
 ```

**Comment by DualTachyon** [comment]
I haven't tried your repo in a while, but I was able to fix my own loader problem (I don't know exactly what it was though!). My loader can be found here:

https://github.com/DualTachyon/dp32g030-flash-loader
